// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.11.0
// source: cachemesh.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheMesh_Get_FullMethodName    = "/pb.CacheMesh/Get"
	CacheMesh_Set_FullMethodName    = "/pb.CacheMesh/Set"
	CacheMesh_Delete_FullMethodName = "/pb.CacheMesh/Delete"
)

// CacheMeshClient is the client API for CacheMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheMeshClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGetSet, error)
	Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGetSet, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error)
}

type cacheMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheMeshClient(cc grpc.ClientConnInterface) CacheMeshClient {
	return &cacheMeshClient{cc}
}

func (c *cacheMeshClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGetSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGetSet)
	err := c.cc.Invoke(ctx, CacheMesh_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheMeshClient) Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGetSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGetSet)
	err := c.cc.Invoke(ctx, CacheMesh_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheMeshClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForDelete)
	err := c.cc.Invoke(ctx, CacheMesh_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheMeshServer is the server API for CacheMesh service.
// All implementations must embed UnimplementedCacheMeshServer
// for forward compatibility.
type CacheMeshServer interface {
	Get(context.Context, *Request) (*ResponseForGetSet, error)
	Set(context.Context, *Request) (*ResponseForGetSet, error)
	Delete(context.Context, *Request) (*ResponseForDelete, error)
	mustEmbedUnimplementedCacheMeshServer()
}

// UnimplementedCacheMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheMeshServer struct{}

func (UnimplementedCacheMeshServer) Get(context.Context, *Request) (*ResponseForGetSet, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCacheMeshServer) Set(context.Context, *Request) (*ResponseForGetSet, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedCacheMeshServer) Delete(context.Context, *Request) (*ResponseForDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCacheMeshServer) mustEmbedUnimplementedCacheMeshServer() {}
func (UnimplementedCacheMeshServer) testEmbeddedByValue()                   {}

// UnsafeCacheMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheMeshServer will
// result in compilation errors.
type UnsafeCacheMeshServer interface {
	mustEmbedUnimplementedCacheMeshServer()
}

func RegisterCacheMeshServer(s grpc.ServiceRegistrar, srv CacheMeshServer) {
	// If the following call panics, it indicates UnimplementedCacheMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheMesh_ServiceDesc, srv)
}

func _CacheMesh_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheMeshServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheMesh_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheMeshServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheMesh_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheMeshServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheMesh_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheMeshServer).Set(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheMesh_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheMeshServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheMesh_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheMeshServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheMesh_ServiceDesc is the grpc.ServiceDesc for CacheMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CacheMesh",
	HandlerType: (*CacheMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CacheMesh_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _CacheMesh_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CacheMesh_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cachemesh.proto",
}
